language: php
matrix:
  fast_finish: true
  include:
    - php: 5.2
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: TEST_COVERAGE=1
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: 7.0

before_script:
 # Setup the test server
 - phpenv local 5.5
 - composer install --dev --no-interaction

 - TESTPHPBIN=$(phpenv which php)
 - sudo PHPBIN=$TESTPHPBIN vendor/bin/start.sh
 - export REQUESTS_TEST_HOST_HTTP=localhost
 - phpenv local --unset

 # Work out of the tests directory
 - cd tests

script:
 - phpunit --coverage-clover clover.xml

after_script:
 - cd ..
 - phpenv local 5.5
 - sudo PATH=$PATH vendor/bin/stop.sh
 - test $TEST_COVERAGE && bash <(curl -s https://codecov.io/bash)
 - phpenv local --unset
