language: php
before_script:
 # Setup Coveralls and httpbin-php
 - phpenv local 5.5
 - composer install --dev --no-interaction
 - sudo vendor/requests/test-server/bin/start.sh
 - export REQUESTS_TEST_HOST_HTTP=localhost
 - phpenv local --unset

 # Work out of the tests directory
 - cd tests
script:
 - phpunit --coverage-clover clover.xml
after_script:
 - cd ..
 - phpenv local 5.5
 - sudo vendor/requests/test-server/bin/stop.sh
 - php vendor/bin/coveralls -v
 - phpenv local --unset
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - hhvm
