language: php
before_script:
 - phpenv local 5.4
 - composer install --dev --no-interaction
 - phpenv local --unset
 - cd tests
script:
 - phpunit --coverage-clover clover.xml
after_script:
 - phpenv local 5.4
 - php vendor/bin/coveralls -v
 - phpenv local --unset
php:
  - 5.2
  - 5.3
  - 5.4