language: php
before_script:
 # Setup Coveralls and httpbin-php
 - phpenv local 5.5
 - composer install --dev --no-interaction

 - TESTPHPBIN=$(phpenv which php)
 - sudo PHPBIN=$TESTPHPBIN vendor/bin/start.sh
 - export REQUESTS_TEST_HOST_HTTP=localhost
 - phpenv local --unset

 # Work out of the tests directory
 - cd tests
script:
 - phpunit --coverage-clover clover.xml
after_script:
 - cd ..
 - phpenv local 5.5
 - sudo PATH=$PATH vendor/bin/stop.sh
 - test $TEST_COVERAGE && php vendor/bin/coveralls -v
 - phpenv local --unset
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  # We include 5.6 too, but in the matrix to enable coverage too
  - 7.0
  - hhvm
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
  include:
    - php: 5.6
      env: TEST_COVERAGE=1
